//! # CRC-16/CCITT-FALSE — port of `Svc::Ccsds::Utils::CRC16`
//!
//! C++ sources: `Svc/Ccsds/Utils/CRC16.hpp` over the vendored libcrc
//! `update_crc_ccitt` (`Utils/Hash/libcrc/lib_crc.c`).
//! Analysis: `docs/cpp-analysis/ccsds.md` ("Utils::CRC16" and
//! "Frame Error Control Field").
//!
//! This is the Frame Error Control Field (FECF) checksum of the CCSDS TM and
//! TC transfer frames: polynomial `0x1021`, initial value `0xFFFF`,
//! **non-reflected** input and output, final XOR `0x0000`. It is a different
//! algorithm from the F Prime frame CRC-32/ISO-HDLC used by
//! [`crate::fprime_framer`] — the two must never share code.
//!
//! The 256-entry table is generated by a `const fn` at compile time (the C++
//! builds it lazily at first use), so this module is allocation-free and has
//! no initialization order.

/// CRC-16/CCITT generator polynomial (libcrc `P_CCITT`).
pub const POLYNOMIAL: u16 = 0x1021;
/// Initial CRC register value (`std::numeric_limits<U16>::max()`).
pub const INIT: u16 = 0xFFFF;
/// Final XOR value (the C++ `finalize()` XORs with 0).
pub const XOR_OUT: u16 = 0x0000;

/// The MSB-first (non-reflected) CRC-16/CCITT byte table, built at compile
/// time exactly as libcrc's `init_crcccitt_tab` builds it at run time.
const TABLE: [u16; 256] = build_table();

/// Build the byte-wise CRC table for [`POLYNOMIAL`], MSB-first.
const fn build_table() -> [u16; 256] {
    let mut table = [0u16; 256];
    let mut i = 0usize;
    while i < 256 {
        let mut crc = (i as u16) << 8;
        let mut bit = 0;
        while bit < 8 {
            crc = if crc & 0x8000 != 0 {
                (crc << 1) ^ POLYNOMIAL
            } else {
                crc << 1
            };
            bit += 1;
        }
        table[i] = crc;
        i += 1;
    }
    table
}

/// Streaming CRC-16/CCITT-FALSE calculator (`Svc::Ccsds::Utils::CRC16`).
///
/// Byte-at-a-time [`update`](Crc16::update) is what the uplink frame
/// detector needs when it peeks a ring buffer; [`compute`](Crc16::compute)
/// is the one-shot form used by the framers and deframers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Crc16 {
    /// The CRC register (C++ public member `m_crc`).
    crc: u16,
}

impl Default for Crc16 {
    fn default() -> Self {
        Self::new()
    }
}

impl Crc16 {
    /// A calculator with the register at [`INIT`] (the C++ constructor).
    #[must_use]
    pub const fn new() -> Self {
        Self { crc: INIT }
    }

    /// Add one byte to the calculation (C++ `update`).
    pub fn update(&mut self, new_byte: u8) {
        let tmp = ((self.crc >> 8) ^ u16::from(new_byte)) as u8;
        self.crc = (self.crc << 8) ^ TABLE[tmp as usize];
    }

    /// Add a slice of bytes, in order.
    pub fn update_all(&mut self, bytes: &[u8]) {
        for &byte in bytes {
            self.update(byte);
        }
    }

    /// The CRC value for everything added so far (C++ `finalize`: XOR with
    /// [`XOR_OUT`], leaving the register untouched).
    #[must_use]
    pub const fn finalize(&self) -> u16 {
        self.crc ^ XOR_OUT
    }

    /// The raw register value (C++ public `m_crc`).
    #[must_use]
    pub const fn register(&self) -> u16 {
        self.crc
    }

    /// One-shot CRC over `buffer` (C++ `CRC16::compute`).
    #[must_use]
    pub fn compute(buffer: &[u8]) -> u16 {
        let mut crc = Self::new();
        crc.update_all(buffer);
        crc.finalize()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    /// The canonical CRC-16/CCITT-FALSE check value.
    #[test]
    fn check_value_of_123456789() {
        assert_eq!(Crc16::compute(b"123456789"), 0x29B1);
    }

    /// The empty message returns the initial value unchanged.
    #[test]
    fn empty_input_is_init_value() {
        assert_eq!(Crc16::compute(&[]), 0xFFFF);
        assert_eq!(Crc16::new().finalize(), 0xFFFF);
    }

    /// Published CRC-16/CCITT-FALSE vectors (cross-checked against an
    /// independent implementation).
    #[test]
    fn literal_vectors() {
        assert_eq!(Crc16::compute(&[0x00]), 0xE1F0);
        assert_eq!(Crc16::compute(&[0x00, 0x00]), 0x1D0F);
        assert_eq!(Crc16::compute(&[0xFF]), 0xFF00);
        assert_eq!(Crc16::compute(&[0xA5]), 0x04BF);
        assert_eq!(Crc16::compute(b"A"), 0xB915);
        assert_eq!(Crc16::compute(b"CCSDS"), 0xB7F6);
        assert_eq!(Crc16::compute(&[0x01, 0x02, 0x03, 0x04]), 0x89C3);
    }

    /// Streaming byte-by-byte equals the one-shot computation (the frame
    /// detector peeks a ring buffer one byte at a time).
    #[test]
    fn streaming_matches_one_shot() {
        let data: Vec<u8> = (0u8..=255).collect();
        let mut crc = Crc16::new();
        for &byte in &data {
            crc.update(byte);
        }
        assert_eq!(crc.finalize(), Crc16::compute(&data));
    }

    /// Appending the big-endian CRC to a message makes the CRC of the whole
    /// message zero — the property the CCSDS FECF relies on.
    #[test]
    fn appending_crc_yields_zero_residue() {
        let mut msg = b"CCSDS TM FRAME".to_vec();
        let crc = Crc16::compute(&msg);
        msg.extend_from_slice(&crc.to_be_bytes());
        assert_eq!(Crc16::compute(&msg), 0x0000);
    }

    /// The table is the MSB-first 0x1021 table (spot values).
    #[test]
    fn table_entries_match_polynomial() {
        assert_eq!(TABLE[0], 0x0000);
        assert_eq!(TABLE[1], 0x1021);
        assert_eq!(TABLE[2], 0x2042);
        assert_eq!(TABLE[255], 0x1EF0);
    }

    /// `finalize` is non-mutating (C++ parity: the register survives).
    #[test]
    fn finalize_does_not_consume_state() {
        let mut crc = Crc16::new();
        crc.update_all(b"1234");
        let first = crc.finalize();
        assert_eq!(first, crc.finalize());
        crc.update_all(b"56789");
        assert_eq!(crc.finalize(), 0x29B1);
        assert_eq!(crc.register(), 0x29B1);
    }
}
